### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by strebl** [JadenGeller/Helium#182]
Hi I'm using Helium a long time now.
And I really like it! Fantastic job!
But I saw great improvements in the commits, which aren't available to the users because there is no recent release available 🙁

Do you plan to push a release soon?
I tried to build it myself with following command `xcodebuild -project Helium.xcodeproj build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO` which failed:

```
=== BUILD TARGET HeliumShareExtension OF PROJECT Helium WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
"HeliumShareExtension" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)
```

Has someone a easy fix for that?

**Comment by strebl** [comment]
Ok now it worked. I opened the project in Xcode an converted the project to Swift 2.3.

After that the build failed with various errors. I updated the source until all compile errors where gone.

You'll find my code here: https://github.com/strebl/Helium/tree/swift-2.3

I didn't create a pull request because it was the first time I saw Swift code and native app code at all. Therefore I have no idea if my changes work in every scenario.
Because I didn't see any tests, I can't run them neither. 

I'm happy to create a pull request if that will help you.

Again, great project @JadenGeller!

**Comment by JadenGeller** [comment]
Hi @strebl! Thanks for looking into this. I haven't touched the project much now that the upcoming version of macOS natively supports picture-in-picture. I realize this doesn't cover all use cases of Helium, but I don't think it's worth it to me to support it any longer.

That said, I would definitely accept pull requests if you'd like to contribute!

**Comment by xenio** [comment]
@strebl Do you have a working build? Or how do you fix the missing signature in XCODE?

**Comment by strebl** [comment]
I'm on holidays until tuesday. I do not have my macbook with me. I'll look into that when I'm back.
But if I remember correctly, I pushed my changes to my fork. Maybe that fork will work for you too.
I used the latest Xcode at that time.


Am 10.10.2016 um 12:57 schrieb Sandro Forbice <notifications@github.com<mailto:notifications@github.com>>:


@strebl<https://github.com/strebl> Do you have a working build? Or how do you fix the missing signature in XCODE?

-

**Comment by jpshelley** [comment]
For what its worth, the macOS PiP is terrible (no transluency and very few support it.) There is a safari extension that helps but still isn't the greatest. I think it would be great to continue this project.

**Comment by anthonyattard** [comment]
How can I build the latest version? So many errors when done from the current source.
